In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
arr_random = np.random.randint(low = 2, high = 10, size=(4,4))
arr_random

array([[4, 2, 3, 3],
       [4, 9, 6, 8],
       [6, 3, 3, 4],
       [5, 6, 4, 4]])

In [ ]:
pd.DataFrame(arr_random, columns = ["Random value 1", "Random value 2", "Random value 3", "Random value 4"])

   Random value 1  Random value 2  Random value 3  Random value 4
0               4               2               3               3
1               4               9               6               8
2               6               3               3               4
3               5               6               4               4

In [ ]:
df.describe(include='all')

               0          1          2          3
count   4.000000   4.000000   4.000000   4.000000
mean    7.000000   8.000000   9.000000  10.000000
std     5.163978   5.163978   5.163978   5.163978
min     1.000000   2.000000   3.000000   4.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     7.000000   8.000000   9.000000  10.000000
75%    10.000000  11.000000  12.000000  13.000000
max    13.000000  14.000000  15.000000  16.000000

In [ ]:
df.isnull().any()

0    False
1    False
2    False
3    False
dtype: bool

In [ ]:
df.loc[:, 2:3]

    2   3
0   3   4
1   7   8
2  11  12
3  15  16

In [ ]:
df.iloc[0:4, 2:4]

    2   3
0   3   4
1   7   8
2  11  12
3  15  16